// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Owlbear.Model;

namespace Owlbear.Migrations
{
    [DbContext(typeof(OwlbearContext))]
    [Migration("20210429111810_TweetsRemoteId")]
    partial class TweetsRemoteId
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "5.0.5");

            modelBuilder.Entity("Owlbear.Model.Creator", b =>
                {
                    b.Property<int>("CreatorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TwitchTwitterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TwitterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YoutubeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CreatorId");

                    b.HasIndex("TwitchTwitterId");

                    b.HasIndex("TwitterId");

                    b.HasIndex("YoutubeId");

                    b.ToTable("Creators");
                });

            modelBuilder.Entity("Owlbear.Model.CreatorRecord", b =>
                {
                    b.Property<int>("CreatorRecordId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("CreatorId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Date")
                        .HasColumnType("date");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TwitchTwitterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("TwitterId")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("YoutubeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CreatorRecordId");

                    b.HasIndex("TwitchTwitterId");

                    b.HasIndex("TwitterId");

                    b.HasIndex("YoutubeId");

                    b.ToTable("CreatorArchive");
                });

            modelBuilder.Entity("Owlbear.Model.Tweet", b =>
                {
                    b.Property<int>("TweetId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Likes")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Quotes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Replies")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Retweets")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("TwitterId")
                        .HasColumnType("INTEGER");

                    b.HasKey("TweetId");

                    b.HasIndex("TwitterId");

                    b.ToTable("Tweet");
                });

            modelBuilder.Entity("Owlbear.Model.Twitch", b =>
                {
                    b.Property<int>("TwitterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Followers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("OfflineImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProfileImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<int>("RemoteId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteLogin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Views")
                        .HasColumnType("INTEGER");

                    b.HasKey("TwitterId");

                    b.ToTable("Twitch");
                });

            modelBuilder.Entity("Owlbear.Model.Twitter", b =>
                {
                    b.Property<int>("TwitterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("Followers")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Handle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ImageUrl")
                        .HasColumnType("TEXT");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("TwitterId");

                    b.ToTable("Twitter");
                });

            modelBuilder.Entity("Owlbear.Model.Youtube", b =>
                {
                    b.Property<int>("YoutubeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("RemoteId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("Subscribers")
                        .HasColumnType("INTEGER");

                    b.Property<long>("TotalViews")
                        .HasColumnType("INTEGER");

                    b.HasKey("YoutubeId");

                    b.ToTable("Youtube");
                });

            modelBuilder.Entity("Owlbear.Model.Creator", b =>
                {
                    b.HasOne("Owlbear.Model.Twitch", "Twitch")
                        .WithMany()
                        .HasForeignKey("TwitchTwitterId");

                    b.HasOne("Owlbear.Model.Twitter", "Twitter")
                        .WithMany()
                        .HasForeignKey("TwitterId");

                    b.HasOne("Owlbear.Model.Youtube", "Youtube")
                        .WithMany()
                        .HasForeignKey("YoutubeId");

                    b.Navigation("Twitch");

                    b.Navigation("Twitter");

                    b.Navigation("Youtube");
                });

            modelBuilder.Entity("Owlbear.Model.CreatorRecord", b =>
                {
                    b.HasOne("Owlbear.Model.Twitch", "Twitch")
                        .WithMany()
                        .HasForeignKey("TwitchTwitterId");

                    b.HasOne("Owlbear.Model.Twitter", "Twitter")
                        .WithMany()
                        .HasForeignKey("TwitterId");

                    b.HasOne("Owlbear.Model.Youtube", "Youtube")
                        .WithMany()
                        .HasForeignKey("YoutubeId");

                    b.Navigation("Twitch");

                    b.Navigation("Twitter");

                    b.Navigation("Youtube");
                });

            modelBuilder.Entity("Owlbear.Model.Tweet", b =>
                {
                    b.HasOne("Owlbear.Model.Twitter", null)
                        .WithMany("Tweets")
                        .HasForeignKey("TwitterId");
                });

            modelBuilder.Entity("Owlbear.Model.Twitter", b =>
                {
                    b.Navigation("Tweets");
                });
#pragma warning restore 612, 618
        }
    }
}
